title: Johann Wiedmeier
description: Software Engineer & Architect
baseurl: "" # leave empty for user site

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# Navigation
navigation:
  - title: Home
    url: /
  - title: Resume
    url: /resume
  - title: Blog
    url: /blog
  - title: Imprint
    url: /imprint 

# Blog settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Johann Wiedmeier"
      
# Plugins
plugins:
  - jekyll-feed 